### ISSUE TITLE
Adding Home Assistant to Netdata Cloud

### ISSUE THREAD

**Issue by Mage86** [Gamma-Software/netdata-homeassistant-addon#1]
Would be nice to allow some setting or script execution to add Home Assistant to netdata cloud nodes so I can access it from central place for all my servers

**Comment by Gamma-Software** [comment]
for the connection to the Netdata cloud, that's exactly what the merge request https://github.com/Gamma-Software/netdata-homeassistant-addon/pull/2#issue-1155016380 does.
I'll keep the issue here to track the progression.

**Comment by Gamma-Software** [comment]
I managed to connect to my cloud instance but without ingress mode.
I'll keep searching for a better solution. (to use a more secure way to connect the node)

**Comment by Gamma-Software** [comment]
even when we proxy by ingress, the connection to the cloud works.
I'll push that update.
And generate a new release

**Comment by Gamma-Software** [comment]
Hum can't make it work anymore after refresh install ...
I'll try to find the solution

**Comment by Gamma-Software** [comment]
Ok I found the solution but now when I restart the addon, multiple instance of homassistant in netdata cloud are displayed

**Comment by Gamma-Software** [comment]
@Mage86 You can try 2.1.0 to connect your home assistant netdata instance.
Give it a shoot and give me some feedbacks :) I'll be please ;)

**Comment by Mage86** [comment]
@Gamma-Software can you please send sample configuration.yaml file for those settings? 

I tried to add them according to docs but it doesn't seem to read them and I don't want to change config directly on module file (it will be overwritten probably on update).

**Comment by Gamma-Software** [comment]
Something like that:

```
hostname: homeassistant
page_cache_size: 32
dbengine_disk_space: 256
enable_alarm: true
enable_log: true
claim_url: https://app.netdata.cloud
claim_token: >-
  7DsyzhlmxR9zV8_WZqdb14oY6JCrCWMRMzE0nL_8Wi1yZTOWtAXuN2WlR4Gu8xpYht2WeN3g2zD4QJ6DslXzOlwo-w9gNuNBJxBulSBCyNZsM_kqcRZhS8bds8OGEzC_ej_CKsD
claim_rooms:
  - 5823aab7-fd01-7695-t939-741f58b6de19
```

What's in the log ?

**Comment by Gamma-Software** [comment]
@Mage86  Does it work ?
